FORMAT: 1A
HOST: http://contract-service-base-uriDefaultValue/api

# Contract Service
## Authentication
This API uses JSON Web Tokens for its authentication.

The parameters that are needed to be sent for this type of authentication are as follows:
+ `JWTHeaderName`
+ `JWTAcquireURL`
+ `JWTDestroyURL`

# Group contracts

Methods for contract resources

## Contracts [/contracts]

### Adds a new contract [POST]
Method to add a new contract. Users only with Administrator role can invoke this method.

+ Request (application/json)

    + Attributes (NewContract)



+ Response 200 (application/json)

        Successful operation

    + Attributes (Contract)



+ Response 400 

        Validation failed




+ Response 401 

        Missing/invalid access token or role not valid for the operation





## Contracts [/contracts{?contractorsName,pageNum,pageSize}]

### Retrieves contracts [GET]
Method to retrieve multiple contracts. Use allowed query parameters to filter and pagination. Users only with Administrator and Resident roles can invoke this method.
+ Parameters
    + contractorsName (string, optional)

        Contractors name to filter by

    + pageNum (number, optional) -

        Page number for the pagination.

        + Default: 1 (only if pageSize is present)
    + pageSize (number, optional) -

        Page size for the pagination.

        + Default: 20 (only if pageNum is present)

+ Response 200 (application/json)

        Successful operation

    + Attributes (Contracts)



+ Response 401 

        Missing/invalid access token or role not valid for the operation





## Contracts By Contract Id [/contracts/{contract_id}]

+ Parameters
    + contract_id (string, required)

        ID of the contract to be retreived


### Retrieves a contract [GET]
Method to retrieve a partucular contract. Users only with Administrator and Resident roles can invoke this method.

+ Response 200 (application/json)

        Successful operation

    + Attributes (Contract)



+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No contract found with the specified ID





## Contracts Confirmation By Contract Id [/contracts/{contract_id}/confirmation]

+ Parameters
    + contract_id (string, required)

        Contract ID


### Confirms a contract [PUT]
Method to confirm a partucular contract. A contract can only be confirmed no later than two weeks after it's creation. Users only with Resident role can invoke this method.

+ Response 201 



+ Response 400 

        Validation failed




+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No contract found with the specified ID





## Contracts Extension By Contract Id [/contracts/{contract_id}/extension]

+ Parameters
    + contract_id (string, required)

        Contract ID


### Extends a contract [PUT]
Method to extend a partucular contract. A contract can only be extended no later than three months before it's current end date and maximum for six months only. Users only with Resident role can invoke this method.

+ Request (application/json)

    + Attributes (UpdateContract)



+ Response 201 



+ Response 400 

        Validation failed




+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No contract found with the specified ID





## Contracts Termination By Contract Id [/contracts/{contract_id}/termination]

+ Parameters
    + contract_id (string, required)

        Contract ID


### Terminates a contract [PUT]
Method to extend a partucular contract. A contract can only be terminated no later than three months before it's current end date and maximum for six months only. Users only with Resident role can invoke this method.

+ Request (application/json)

    + Attributes (UpdateContract)



+ Response 201 



+ Response 400 

        Validation failed




+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No contract found with the specified ID






# Data Structures

## NewContract (object)


### Properties
+ `contractorsName` (string, optional) 
+ `contractorsEmail` (string, optional) 
+ `contractorsPhone` (string, optional) 
+ `roomNumber` (string, optional) 
+ `startDate` (string, optional) 
+ `endDate` (string, optional) 
+ `status` (enum[string], optional) - Contract Status
    + `confirmed`
    + `unconfirmed`


## Contract (object)


### Properties
+ `contractId` (string, optional) 
+ `contractorsName` (string, optional) 
+ `contractorsEmail` (string, optional) 
+ `contractorsPhone` (string, optional) 
+ `roomNumber` (string, optional) 
+ `startDate` (string, optional) 
+ `endDate` (string, optional) 
+ `status` (enum[string], optional) - Contract Status
    + `confirmed`
    + `unconfirmed`
+ `_links` (Links, optional) 


## Contracts (object)


### Properties
+ `data` (array[Contract], optional) 
+ `_links` (Links1, optional) 


## UpdateContract (object)


### Properties
+ `newEndDate` (string, optional) 


## Links (object)


### Properties
+ `self` (Self, optional) 


## Links1 (object)


### Properties
+ `next` (Next, optional) 
+ `prev` (Prev, optional) 


## Next (object)


### Properties
+ `href` (string, optional) 


## Prev (object)


### Properties
+ `href` (string, optional) 


## Self (object)


### Properties
+ `href` (string, optional) 

