FORMAT: 1A
HOST: http://caretaker-service-base-uriDefaultValue/api

# Caretaker Service
## Authentication
This API uses JSON Web Tokens for its authentication.

The parameters that are needed to be sent for this type of authentication are as follows:
+ `JWTHeaderName`
+ `JWTAcquireURL`
+ `JWTDestroyURL`

# Group appointments

Methods for appoinment resources

## Appoinments [/appoinments]

### Adds a new appoinment [POST]
Method to add a new appoinment. Users only with Resident role can invoke this method. Move In appoinntment can only be added only after the confirmation of the contract. Move Out appointment can only be added no earlier than three months before the contract's current end date.

+ Request (application/json)

    + Attributes (NewAppointment)



+ Response 200 (application/json)

        Successful operation

    + Attributes (Appointment)



+ Response 400 

        Validation failed




+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No appointment found with the specified id





## Appoinments [/appoinments{?date,pageNum,pageSize}]

### Retrieves appointments [GET]
Method to retrieve multiple appointments. Use allowed query parameters to filter and pagination. Users with Administrator, Caretaker and Resident roles can invoke this method.
+ Parameters
    + date (string, optional)

        Date to filter by

    + pageNum (number, optional) -

        Page number for the pagination.

        + Default: 1 (only if pageSize is present)
    + pageSize (number, optional) -

        Page size for the pagination.

        + Default: 20 (only if pageNum is present)

+ Response 200 (application/json)

        Successful operation

    + Attributes (Appointments)



+ Response 401 

        Missing/invalid access token or role not valid for the operation





## Appointments By Appointment Id [/appointments/{appointment_id}]

+ Parameters
    + appointment_id (string, required)

        ID of the appointment to be retreived


### Retrieves an appointment [GET]
Method to retrieve a partucular appointment. Users with Administrator, Caretaker and Resident roles can invoke this method.

+ Response 200 (application/json)

        Successful operation

    + Attributes (Appointment)



+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No appointment found with the specified ID





## Appointments Acceptance [/appointments/{appointment_id}/acceptance]

+ Parameters
    + appointment_id (string, required)

        appointment ID


### Confirms an appointment [PUT]
Method to confirm a partucular appointment. An appointment can only be confirmed no later than two weeks after it's creation. Users only with Resident role can invoke this method.

+ Response 201 



+ Response 400 

        Validation failed




+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No contract found with the specified ID






# Data Structures

## NewAppointment (object)


### Properties
+ `contractId` (string, optional) 
+ `contractorsName` (string, optional) 
+ `roomNumber` (string, optional) 
+ `issue` (string, optional) 
+ `priorityLevel` (enum[string], optional) 
    + `low`
    + `normal`
    + `high`
+ `date` (string, optional) 
+ `appointmentType` (enum[string], optional) 
    + `moveIn`
    + `moveOut`
    + `miscellaneous`


## Appointment (object)


### Properties
+ `appointmentId` (string, optional) 
+ `contractId` (string, optional) 
+ `contractorsName` (string, optional) 
+ `roomNumber` (string, optional) 
+ `issue` (string, optional) 
+ `priorityLevel` (enum[string], optional) 
    + `low`
    + `normal`
    + `high`
+ `date` (string, optional) 
+ `appointmentType` (enum[string], optional) 
    + `moveIn`
    + `moveOut`
    + `miscellaneous`
+ `_links` (Links, optional) 


## Appointments (object)


### Properties
+ `data` (array[Appointment], optional) 
+ `_links` (Links1, optional) 


## Links (object)


### Properties
+ `self` (Self, optional) 


## Links1 (object)


### Properties
+ `next` (Next, optional) 
+ `prev` (Prev, optional) 


## Next (object)


### Properties
+ `href` (string, optional) 


## Prev (object)


### Properties
+ `href` (string, optional) 


## Self (object)


### Properties
+ `href` (string, optional) 

