#%RAML 1.0
title: Contract Service
version: 1.0.0 
baseUri: http://{contract-service-base-uri}/api
mediaType: [application/json, application/xml]
securitySchemes:
   bearerAuth:
     type: Pass Through
     description: JWT authentication
     
types:
  BaseContract:
    type: object
    properties:
      contractorsUserId:
        type: string
        required: true
        description: A valid resident user id is required.
      contractorsName:
        type: string
        required: true
      contractorsEmail:
        type: string
        required: true
      contractorsPhone:
        type: string
        required: true
      roomNumber:
        type: string
        required: true
      startDate:
        type: date-only
        required: true
      endDate:
        type: date-only
        required: true
      status:
        type: array
        description: contract status
        items:
          enum:
            - confirmed
            - unconfirmed
    xml:
      name: NewContract

  ContractResponse:
    type: object
    properties:
      baseContract: BaseContract
      contractId:
        type: string
      createdBy:
        type: string
      createdOn:
        type: date-only    
      links:
        type: array
        items:
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
    xml:
      name: ContractResponse
      
  ContractListResponse:
    type: object
    properties:
      contracts:
        type: array
        items: 
          - ContractResponse
        xml:
          wrapped: true  
    xml:
      name: ContractListResponse

  PaginatedContracts:
    type: object
    properties: 
      contracts: 
        type: array
        items:
          - ContractResponse
        xml:
          wrapped: true
      metadata:
        type: object
        properties: 
          previous: 
            type: string
          next:
            type: string
          first:
            type: string
          last:
            type: string
    xml:
      name: PaginatedContracts                      
  UpdateContractRequest:
    type: object
    properties: 
      operation: 
        type: string
        required: true
        enum:
          - Accept
          - Deny
    xml:
      name: UpdateContractRequest   

/contracts:
  post:
    description: Method to add a new contract. Users only with Admin role can invoke this method.
    body:
      application/json:
        type: BaseContract
      application/xml:
        type: BaseContract
    responses:
      200:
        description: successful operation
        body:
          application/json:
            type: ContractResponse
          application/xml:
            type: ContractResponse
      400:
        description: Validation failed.
      401:
        description: Missing/invalid/expired access token or role not valid for the operation.
      412:
        description: Invalid operation.
      500:
        description: Internal server error.
    securedBy:
      - bearerAuth
  get:
    description: Method to retrieve multiple contracts. Use allowed query parameters to filter and pagination. Users only with Admin role can invoke this method.
    queryParameters:
      contractorsName:
        description: Contractors name to filter by.
        required: false
        type: string
      pageNum:
        description: Page number for the pagination.
        required: false
        type: integer
        default: 1 #only if pageNum is present
      pageSize:
        description: Page size for the pagination.
        required: false
        type: integer
        default: 20 #only if pageSize is present
    responses:
      200:
        description: successful operation
        body:
          application/json:
            type: PaginatedContracts
          application/xml:
            type: PaginatedContracts
      401:
        description: Missing/invalid/expired access token or role not valid for the operation.
      500:
        description: Internal server error.  
    securedBy:
      - bearerAuth

  /{contract-id}:
    uriParameters:
        contract-id: string
    get:
      description: Method to retrieve a particular contract. Users only with Admin and Resident roles can invoke this method. Resident users can retreive only their contracts. If a resident user invokes the method to retreive other resident user's contrct then an unaothorized error response (HTTP response code 401) will be thrown.
      responses:
        200:
          description: successful operation
          body:
            application/json:
              type: ContractResponse
            application/xml:
              type: ContractResponse
        401:
          description: Missing/invalid/expired access token or role not valid for the operation.
        404:
          description: No resource found with the specified ID.
        500:
          description: Internal server error.
      securedBy:
        - bearerAuth
    put:
      description: Method to confirm/extend/terminate a particular contract. Users only with Resident role can invoke this method. Resident users can confirm/extend/confirm only their contracts. A contract can only be confirmed no later than two (2) weeks after it's creation. A cotract can only be extended/terminateed no later than three (3) months before it's current end date. Maximum extention period is six (6) months.
      body:
        application/json:
          type: UpdateContractRequest        
        application/xml:
          type: UpdateContractRequest
      responses:
        200:
          description: successful operation
        401:
          description: Missing/invalid/expired access token or role not valid for the operation.
        404:
          description: No resource found with the specified ID.
        412:
          description: Invalid operation..
        500:
          description: Internal server error. 
      securedBy:
        - bearerAuth
/contractors/{contractors-user-id}/contracts:
  uriParameters:
        contract-id: string
  get:
    description: Method to retrieve contracts of a particular contractor. Users only with Admin and Resident roles can invoke this method. Resident users can retreive only their contracts. If a resident user invokes the method to retreive other resident user's contrct then an unaothorized error response (HTTP response code 401) will be thrown.      
    responses:
        200:
          description: Successful operation
          body:
            application/json:
              type: ContractListResponse
            application/xml:
              type: ContractListResponse
        401:
          description: Missing/invalid/expired access token or role not valid for the operation.
        404:
          description: No resource found with the specified ID.
        500:
          description: Internal server error.
    securedBy:
        - bearerAuth

